apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7001
  CLUSTER_ID: Orleans-Local
  SERVICE_ID: Snaelro
  BUILD_VERSION: 0.0.1

##Create secrets
##kubectl create secret generic postgres-connection --from-literal=value="Server=192.168.99.100;Port=30302;User Id=rudev;Password=masterkey1;Database=snaelro"