kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 7001 #internal port
    nodePort: 30701 #external port
  type: NodePort