apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      tier: backend
      role: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api
        tier: backend
        role: client
    spec:
      containers:
      - name: snaelro-api
        image: snaelro-api:local
        ports:
        - name: http
          containerPort: 7001
        envFrom:
        - configMapRef:
            name: api-config
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: value
        lifecycle:
          preStop:
            httpGet:
              path: "leave"
              port: 7001
      restartPolicy: Always
      terminationGracePeriodSeconds: 60