kind: Service
apiVersion: v1
metadata:
  name: api-identity-service
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    targetPort: 7003 #internal port
    nodePort: 30703 #external port
  type: NodePort