kind: Service
apiVersion: v1
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432 #internal port
    nodePort: 30700 #external port
    protocol: TCP
  type: NodePort