apiVersion: v1
kind: ConfigMap
metadata:
  name: silo-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7001
  CLUSTER_ID: Orleans-Local
  SERVICE_ID: Snaelro
  SILO_PORT: "11111"
  GATEWAY_PORT: "30000"
  BUILD_VERSION: 0.0.1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: silo-dashboard-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://*:7002
  CLUSTER_ID: Orleans-Local
  SERVICE_ID: Snaelro
  BUILD_VERSION: 0.0.1

##Create secrets
##kubectl create secret generic postgres-connection --from-literal=value="Server=192.168.99.100;Port=30700;User Id=dbuser;Password=dbpassword;Database=snaelro"