apiVersion: apps/v1
kind: Deployment
metadata:
  name: silo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: silo
      tier: backend
      role: host
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: silo
        tier: backend
        role: host
    spec:
      containers:
      - name: snaelro-silo
        image: snaelro-silo:local
        ports:
        - name: http
          containerPort: 7000
        envFrom:
        - configMapRef:
            name: silo-config
        env:
        - name: POSTGRES_CONNECTION
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: value
        lifecycle:
          preStop:
            httpGet:
              path: "leave"
              port: 7000
      restartPolicy: Always
      terminationGracePeriodSeconds: 60