kind: Service
apiVersion: v1
metadata:
  name: silo-service
spec:
  selector:
    app: silo
    tier: backend
    role: host
  ports:
  - name: http
    port: 80
    targetPort: 7001 #internal port
    nodePort: 30701 #external port
  type: NodePort
---
kind: Service
apiVersion: v1
metadata:
  name: silo-dashboard-service
spec:
  selector:
    app: silo
    tier: backend
    role: dashboard
  ports:
  - name: http
    port: 80
    targetPort: 7002 #internal port
    nodePort: 30702 #external port
  type: NodePort
